version: '3.0'

services:

  website:
    image: website
    build:
      context: website
      dockerfile: Dockerfile
    environment: 
      LOGURL: "logstash:5000"
    ports:
      - "80:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
      - ./elk-log-config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.0
    volumes:
      - ./elk-log-config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk-log-config/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    volumes:
      - ./elk-log-config/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
