version: '3.0'

services:

  website:
    image: website
    build:
      context: .
      dockerfile: website/Dockerfile
    environment: 
      LOGURL: "logstash:5000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
      - elk-log-config:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.0
    volumes:
      - elk-log-config:/usr/share/logstash/config
      - elk-log-config:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    volumes:
      - elk-log-config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elk-log-config:      